### ISSUE TITLE
Does not build with php 7.1

### ISSUE THREAD

**Issue by no1youknowz** [andreiz/php-zookeeper#82]
Does not build with 7.1

First error:

	/root/php-zookeeper-master/php_zookeeper.c:38:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 	#include <ext/standard/php_smart_str.h>
                                        ^
	compilation terminated.
	make: *** [php_zookeeper.lo] Error 1

Easy to fix, because php_smart_str -> php_smart_string  with 7.1

Another error:

	/root/php-zookeeper-master/php_zookeeper.c: In function 'zm_startup_zookeeper':
	/root/php-zookeeper-master/php_zookeeper.c:1217:30: warning: assignment from incompatible pointer type [enabled by default]
  	zookeeper_ce->create_object = php_zk_new;
                              ^
	make: *** [php_zookeeper.lo] Error 1

**Comment by Timandes** [comment]
Could you please provide the version of your php-zookeeper?

**Comment by no1youknowz** [comment]
I'm using master from andreiz/php-zookeeper.

Master from Timandes/libzookeeper, compiles with no errors.

Also, pecl install zookeeper-0.3.2, compiles with no errors also.

Which version is best to use?  I am confused.

Thanks

**Comment by Timandes** [comment]
Try pecl/zookeeper.
Enjoy it.

**Comment by no1youknowz** [comment]
Many thanks!
